# Generated by Django 5.0.3 on 2024-05-12 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_Modules(apps, schema_editor):
    Roles = apps.get_model('Users', 'Module')
    datos = [
        {'name': 'Ventas'},
        {'name': 'Nomina'},
        {'name': 'Facturacion'},
        {'name': 'Inventario'},
        {'name': 'Usuarios'}
    ]
    for dato in datos:
        Roles.objects.create(**dato)


def create_roles(apps, schema_editor):
    Roles = apps.get_model('Users', 'role')
    datos = [
        {'name': 'Raiz'},
        {'name': 'Nomina'},
        {'name': 'Ventas'},
        {'name': 'Contabilidad'},
        {'name': 'Inventario'}
    ]
    for dato in datos:
        Roles.objects.create(**dato)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Company", "0002_alter_company_nit"),
    ]

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="profile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=45)),
                ("lastname", models.CharField(max_length=45)),
                ("phone", models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.CharField(max_length=45, unique=True)),
                ("password", models.CharField(max_length=150)),
                ("type", models.CharField(default="E", max_length=2)),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Company.company",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Users.profile"
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Users.role"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("permise_view_or_modify", models.CharField(max_length=2)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Users.module"
                    ),
                ),
                (
                    "account_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),migrations.RunPython(create_Modules),
        migrations.RunPython(create_roles),
    ]
