# Generated by Django 5.0.3 on 2024-04-30 02:00

import django.db.models.deletion
from django.db import migrations, models


def create_Modules(apps, schema_editor):
    Roles = apps.get_model('Users', 'Module')
    datos = [
        {'name': 'Ventas'},
        {'name': 'Nomina'},
        {'name': 'Facturacion'},
        {'name': 'Inventario'},
        {'name': 'Usuarios'}
    ]
    for dato in datos:
        Roles.objects.create(**dato)

def create_roles(apps, schema_editor):
    Roles = apps.get_model('Users', 'role')
    datos = [
        {'name': 'Raiz', 'module_id': 5},
        {'name': 'Nomina', 'module_id': 2},
        {'name': 'Ventas', 'module_id': 1},
        {'name': 'Contabilidad', 'module_id': 3},
        {'name': 'Inventario', 'module_id': 4}
    ]
    for dato in datos:
        Roles.objects.create(**dato)



class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="profile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=45)),
                ("lastname", models.CharField(max_length=45)),
                ("phone", models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=45)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Users.module"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("permise_view_or_modify", models.CharField(max_length=2)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Users.module"
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Users.role"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=45)),
                ("password", models.CharField(max_length=45)),
                ("type", models.CharField(default="E", max_length=2)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Company.company",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Users.profile"
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Users.role"
                    ),
                ),
            ],
        ), migrations.RunPython(create_Modules),  migrations.RunPython(create_roles),
    ]
