# Generated by Django 5.0.3 on 2024-04-27 23:59

import django.db.models.deletion
from django.db import migrations, models


def create_roles(apps, schema_editor):
    Roles = apps.get_model('Users', 'role')
    datos = [
        {'name': 'Raiz'},
        {'name': 'Nomina'},
        {'name': 'Ventas'},
        {'name': 'Contabilidad'},
        {'name': 'Inventario'}
    ]
    for dato in datos:
        Roles.objects.create(**dato)




class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="company",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("NIT", models.CharField(max_length=45)),
                ("businessArea", models.CharField(max_length=45)),
                ("employeeNumber", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="profile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=45)),
                ("lastname", models.CharField(max_length=45)),
                ("phone", models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=45)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Users.module"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("permise_view", models.BooleanField(default=False)),
                ("permise_modify", models.BooleanField(default=False)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Users.module"
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Users.role"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=45)),
                ("password", models.CharField(max_length=45)),
                ("type", models.CharField(default="E", max_length=2)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Users.company"
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Users.profile"
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Users.role"
                    ),
                ),
            ],
        ), migrations.RunPython(create_roles),
    ]
