# Generated by Django 5.0.3 on 2024-05-15 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="permission",
            name="modify",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="permission",
            name="view",
            field=models.BooleanField(default=False),
        ),
    ]
