# Generated by Django 5.0.3 on 2024-05-15 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0002_permission_modify_permission_view"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="permission",
            name="permise_view_or_modify",
        ),
    ]
