# Generated by Django 5.0.3 on 2024-04-30 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0002_rename_username_account_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="password",
            field=models.CharField(max_length=150),
        ),
    ]
