# Generated by Django 5.0.3 on 2024-04-30 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Company", "0001_initial"),
        ("Users", "0003_alter_account_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Company.company",
            ),
        ),
    ]
