# Generated by Django 5.0.3 on 2024-05-26 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Company", "0001_initial"),
        ("Users", "0003_remove_permission_permise_view_or_modify"),
    ]

    operations = [
        migrations.CreateModel(
            name="payment",
            fields=[
                ("payment_id", models.IntegerField(primary_key=True, serialize=False)),
                ("method", models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="services",
            fields=[
                ("service_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=45)),
                ("state", models.CharField(max_length=45)),
                ("active", models.IntegerField(default=1)),
                ("users", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="clients",
            fields=[
                ("client_id", models.IntegerField(primary_key=True, serialize=False)),
                ("company_name", models.CharField(max_length=45)),
                ("lastName", models.CharField(max_length=45)),
                ("email", models.EmailField(max_length=45)),
                ("phone", models.CharField(max_length=45)),
                ("address", models.CharField(max_length=45)),
                (
                    "company_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Company.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="coupons",
            fields=[
                (
                    "code",
                    models.CharField(max_length=45, primary_key=True, serialize=False),
                ),
                ("duration", models.IntegerField()),
                ("discount", models.FloatField()),
                ("expiration_date", models.DateField()),
                ("active", models.IntegerField(default=1)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Users.clients"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="plan",
            fields=[
                ("plan_id", models.IntegerField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=45)),
                ("description", models.CharField(max_length=45)),
                ("mensual_price", models.FloatField()),
                ("semestral_price", models.FloatField()),
                ("anual_price", models.FloatField()),
                ("users", models.IntegerField()),
                ("state", models.CharField(max_length=45)),
                ("num_accounts", models.IntegerField()),
                ("num_services", models.IntegerField()),
                ("active", models.IntegerField(default=1)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Company.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="billings",
            fields=[
                (
                    "suscription_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("initial_date", models.DateField()),
                ("final_date", models.DateField()),
                ("amount", models.FloatField()),
                ("coupon", models.CharField(max_length=45)),
                ("active", models.IntegerField(default=1)),
                ("payment_date", models.DateField()),
                ("payment_method", models.CharField(max_length=45)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Users.payment"
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Users.plan"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="plan_has_services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.IntegerField(default=1)),
                (
                    "plan_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Users.plan"
                    ),
                ),
                (
                    "service_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Users.services"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="trials",
            fields=[
                ("trial_id", models.IntegerField(primary_key=True, serialize=False)),
                ("duration", models.IntegerField()),
                ("state", models.CharField(max_length=45)),
                ("active", models.IntegerField(default=1)),
                (
                    "client_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Users.clients"
                    ),
                ),
                (
                    "plan_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Users.plan"
                    ),
                ),
            ],
        ),
    ]
