# Generated by Django 5.0.3 on 2024-05-26 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0004_contactus_payment_services_clients_coupons_plan_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="company",
        ),
    ]
