# Generated by Django 5.0.3 on 2024-04-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0004_alter_account_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="email",
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
