# Generated by Django 5.0.3 on 2024-05-26 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0005_remove_plan_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="plan_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
