# Generated by Django 5.0.3 on 2024-05-26 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0007_alter_plan_description_alter_plan_num_accounts_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plan",
            old_name="type",
            new_name="typePlan",
        ),
    ]
