# Generated by Django 5.0.3 on 2024-04-30 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="company",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("NIT", models.CharField(max_length=45)),
                ("businessArea", models.CharField(max_length=45)),
                ("employeeNumber", models.IntegerField()),
                ("businessName", models.CharField(max_length=45)),
            ],
        ),
    ]
