# Generated by Django 5.0.3 on 2024-05-26 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="branch",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=45)),
                ("address", models.CharField(max_length=45)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Company.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="support",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=45)),
                ("lastname", models.CharField(max_length=45)),
                ("phone", models.CharField(max_length=45)),
                ("email", models.CharField(max_length=45)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Company.company",
                    ),
                ),
            ],
        ),
    ]
